.section .data
.globl app_0_start
.globl app_0_end
.align 3
        app_0_start:
                .incbin "../../misc/syscalltests/syscalltests/dup"
        app_0_end:

.section .data
.globl app_1_start
.globl app_1_end
.align 3
        app_1_start:
                .incbin "../../misc/syscalltests/syscalltests/waitpid"
        app_1_end:

.section .data
.globl app_2_start
.globl app_2_end
.align 3
        app_2_start:
                .incbin "../../misc/syscalltests/syscalltests/fork"
        app_2_end:

.section .data
.globl app_3_start
.globl app_3_end
.align 3
        app_3_start:
                .incbin "../../misc/syscalltests/syscalltests/getppid"
        app_3_end:

.section .data
.globl app_4_start
.globl app_4_end
.align 3
        app_4_start:
                .incbin "../../misc/syscalltests/syscalltests/exit"
        app_4_end:

.section .data
.globl app_5_start
.globl app_5_end
.align 3
        app_5_start:
                .incbin "../../misc/syscalltests/syscalltests/mnt"
        app_5_end:

.section .data
.globl app_6_start
.globl app_6_end
.align 3
        app_6_start:
                .incbin "../../misc/syscalltests/syscalltests/run-all.sh"
        app_6_end:

.section .data
.globl app_7_start
.globl app_7_end
.align 3
        app_7_start:
                .incbin "../../misc/syscalltests/syscalltests/dup2"
        app_7_end:

.section .data
.globl app_8_start
.globl app_8_end
.align 3
        app_8_start:
                .incbin "../../misc/syscalltests/syscalltests/sleep"
        app_8_end:

.section .data
.globl app_9_start
.globl app_9_end
.align 3
        app_9_start:
                .incbin "../../misc/syscalltests/syscalltests/wait"
        app_9_end:

.section .data
.globl app_10_start
.globl app_10_end
.align 3
        app_10_start:
                .incbin "../../misc/syscalltests/syscalltests/test_echo"
        app_10_end:

.section .data
.globl app_11_start
.globl app_11_end
.align 3
        app_11_start:
                .incbin "../../misc/syscalltests/syscalltests/getpid"
        app_11_end:

.section .data
.globl app_12_start
.globl app_12_end
.align 3
        app_12_start:
                .incbin "../../misc/syscalltests/syscalltests/mmap"
        app_12_end:

.section .data
.globl app_13_start
.globl app_13_end
.align 3
        app_13_start:
                .incbin "../../misc/syscalltests/syscalltests/brk"
        app_13_end:

.section .data
.globl app_14_start
.globl app_14_end
.align 3
        app_14_start:
                .incbin "../../misc/syscalltests/syscalltests/munmap"
        app_14_end:

.section .data
.globl app_15_start
.globl app_15_end
.align 3
        app_15_start:
                .incbin "../../misc/syscalltests/syscalltests/pipe"
        app_15_end:

.section .data
.globl app_16_start
.globl app_16_end
.align 3
        app_16_start:
                .incbin "../../misc/syscalltests/syscalltests/clone"
        app_16_end:

.section .data
.globl app_17_start
.globl app_17_end
.align 3
        app_17_start:
                .incbin "../../misc/syscalltests/syscalltests/execve"
        app_17_end:

.section .data
.globl app_18_start
.globl app_18_end
.align 3
        app_18_start:
                .incbin "../../misc/syscalltests/syscalltests/times"
        app_18_end:

